// <auto-generated />
using EntityFrameworkExample;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkExample.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("EntityFrameworkExample.Models.ClassRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoomName");

                    b.HasKey("Id");

                    b.ToTable("ClassRoom");
                });

            modelBuilder.Entity("EntityFrameworkExample.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClassRoomId");

                    b.Property<char>("Grade");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ClassRoomId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("EntityFrameworkExample.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClassRoomId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ClassRoomId");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("EntityFrameworkExample.Models.Student", b =>
                {
                    b.HasOne("EntityFrameworkExample.Models.ClassRoom", "ClassRoom")
                        .WithMany("Students")
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EntityFrameworkExample.Models.Teacher", b =>
                {
                    b.HasOne("EntityFrameworkExample.Models.ClassRoom", "ClassRoom")
                        .WithMany("Teachers")
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
